/// Flutter icons HadWinIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HadWinIcons
///      fonts:
///       - asset: fonts/HadWinIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HadWinIcons {
  HadWinIcons._();

  static const _kFontFam = 'HadWinIcons';
  static const String? _kFontPkg = null;

  static const IconData wallet_business_and_trade = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_education_29 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData line_awesome_wallet_solid = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
